
services:

  martin:
    image: ghcr.io/maplibre/martin
    container_name: martin
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres@db/db
    depends_on:
      - db
    networks:
      - default

  pg_tileserv:
    image: pramsey/pg_tileserv:latest
    container_name: pg_tileserv
    environment:
      - DATABASE_URL=postgres://postgres@db/db
    restart: on-failure
    depends_on:
      - db
    ports:
      - 7800:7800
    networks:
      - default
      
  db:
    image: postgis/postgis:15-3.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    container_name: db
    volumes:
      - ./data:/work
      - pg_db:/var/lib/postgresql/data

    networks:
      - default
      - bridge1

volumes:
  pg_db:

networks:
  default:
  bridge1: